### ISSUE TITLE
zero formula doesn't install dependencies

### ISSUE THREAD

**Issue by zwaldowski** [zero-sh/homebrew-tap#1]
Contrary to what's listed [here](https://github.com/zero-sh/zero.sh#dependencies) and assumed [here](https://github.com/zero-sh/zero.sh/blob/master/setup#L17), `apply-user-defaults`, `mac`, and `stow` aren't installed by the `zero` formula and will fail during those parts of the bootstrap.

**Comment by msanders** [comment]
Fixed, thanks for the report!
